<a href="https://colab.research.google.com/github/yanli499/APS360-Project/blob/Lucy_1/YLL_Facial_Baseline_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bayesian Model https://towardsdatascience.com/estimating-probabilities-with-bayesian-modeling-in-python-7144be007815

Bayesian Linear Regression https://towardsdatascience.com/bayesian-linear-regression-in-python-using-machine-learning-to-predict-student-grades-part-2-b72059a8ac7e

Sklearn Naive Bayes https://towardsdatascience.com/naive-bayes-document-classification-in-python-e33ff50f937e

Geeks for Geeks https://www.geeksforgeeks.org/multiclass-classification-using-scikit-learn/ 

In [0]:
import os
import shutil
import copy
import time
import random
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision
import torchvision.models
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

from PIL import Image
from torchvision import datasets, models, transforms
from torch.optim import lr_scheduler
from torch.autograd import Variable

In [3]:
# Mount our Google Drive
# re-run whenever needed
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
# re-run when needed
# classes are folders in each directory with these names
classes = ['afraid','angry','disgusted','happy','neutral','sad','surprised']

# emotion label for KDEF photos
emotion_code = {"AF":"afraid", "AN":"angry", "DI":"disgusted", "HA":"happy", 
                "NE":"neutral", "SA":"sad", "SU":"surprised"}
emotion_enum = {"afraid":1, "angry":2, "disgusted":3, "happy":4, 
                "neutral":5, "sad":6, "surprised":7}

data_dir='/content/drive/My Drive/Colab Notebooks/Faces/train'

In [18]:
data = []
target = []

for c in classes:
    filepath = data_dir + '/' + c
    print(filepath)
    for file in os.listdir(filepath):
        target.append(emotion_enum[c])
        im = Image.open(filepath + "/" + file)
        im = im.crop((16, 16, 240, 240))
        np_im = np.array(im)
        np_im = np.ravel(np_im)
        data.append(np_im)

/content/drive/My Drive/Colab Notebooks/Faces/train/afraid
/content/drive/My Drive/Colab Notebooks/Faces/train/angry
/content/drive/My Drive/Colab Notebooks/Faces/train/disgusted
/content/drive/My Drive/Colab Notebooks/Faces/train/happy
/content/drive/My Drive/Colab Notebooks/Faces/train/neutral
/content/drive/My Drive/Colab Notebooks/Faces/train/sad
/content/drive/My Drive/Colab Notebooks/Faces/train/surprised


In [19]:
# importing necessary libraries 
from sklearn import datasets 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 

# # loading the dataset
# faces = datasets.fetch_olivetti_faces()
# X = faces.data
# y = faces.target
X = np.array(data)
y = np.array(target)

print(X.shape)
print(y.shape)

# thus, need to create data w shape (7 * 140, 224 * 224) for total # of samples
# and each row = pixel of photo
# target = labels of all samples

# dividing X, y into train and test data 
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0) 

# training a Naive Bayes classifier 
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB().fit(X_train, y_train) 
gnb_predictions = gnb.predict(X_test) 

# accuracy on X_test 
accuracy = gnb.score(X_test, y_test) 
print(accuracy)

# creating a confusion matrix 
cm = confusion_matrix(y_test, gnb_predictions) 
print(cm)

(490, 50176)
(490,)
0.2682926829268293
[[10  2  1  3  0  0  1]
 [ 3  6  1  5  0  0  0]
 [ 6  2  3  6  2  0  0]
 [ 4  1  1 10  0  0  1]
 [ 4  1  2  9  1  0  0]
 [ 5  5  3  5  3  0  0]
 [ 8  1  0  4  1  0  3]]
