<a href="https://colab.research.google.com/github/yanli499/APS360-Project/blob/Lucy_1/YLL_Facial_Baseline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bayesian Model https://towardsdatascience.com/estimating-probabilities-with-bayesian-modeling-in-python-7144be007815

In [0]:
import pymc3 as pm
import numpy as np

alphas = np.array([1, 1, 1])
c = np.array([3, 2, 1])

# Create model
with pm.Model() as model:
    # Parameters of the Multinomial are from a Dirichlet
    parameters = pm.Dirichlet('parameters', a=alphas, shape=3)
    # Observed data is from a Multinomial distribution
    observed_data = pm.Multinomial(
        'observed_data', n=6, p=parameters, shape=3, observed=c)    

In [0]:
with model:
    # Sample from the posterior
    trace = pm.sample(draws=1000, chains=2, tune=500, 
                      discard_tuned_samples=True)

Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Sequential sampling (2 chains in 1 job)
NUTS: [parameters]
100%|██████████| 1500/1500 [00:01<00:00, 758.33it/s]


In [0]:
pm.traceplot(trace)

# pm.traceplot(normal_trace)
# pm.plot_posterior(normal_trace)

ImportError: ignored

Bayesian Linear Regression https://towardsdatascience.com/bayesian-linear-regression-in-python-using-machine-learning-to-predict-student-grades-part-2-b72059a8ac7e

Sklearn Naive Bayes https://towardsdatascience.com/naive-bayes-document-classification-in-python-e33ff50f937e

In [0]:
# turn class labels into numerical
class_num = {""}



df[‘label’] = df[‘category’].apply(lambda x: 0 if x==’Epistemology’ else 1)

In [0]:
df['label'] = df['category'].apply(lambda x: 0 if x=='Epistemology' else 1)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['abstract'], df['label'], random_state=1)

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(strip_accents='ascii', token_pattern=u'(?ui)\\b\\w*[a-z]+\\w*\\b', lowercase=True, stop_words='english')
X_train_cv = cv.fit_transform(X_train)
X_test_cv = cv.transform(X_test)

word_freq_df = pd.DataFrame(X_train_cv.toarray(), columns=cv.get_feature_names())
top_words_df = pd.DataFrame(word_freq.sum()).sort_values(0, ascending=False)

from sklearn.naive_bayes import MultinomialNB
naive_bayes = MultinomialNB()
naive_bayes.fit(X_train_cv, y_train)
predictions = naive_bayes.predict(X_test_cv)

from sklearn.metrics import accuracy_score, precision_score, recall_score
print('Accuracy score: ', accuracy_score(y_test, predictions))
print('Precision score: ', precision_score(y_test, predictions))
print('Recall score: ', recall_score(y_test, predictions))



NameError: ignored

Geeks for Geeks https://www.geeksforgeeks.org/multiclass-classification-using-scikit-learn/ 

In [0]:
# importing necessary libraries 
from sklearn import datasets 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 

# # loading the iris dataset 
# iris = datasets.load_iris() 

# # X -> features, y -> label 
# X = iris.data 
# y = iris.target 


faces = datasets.fetch_olivetti_faces()
X = faces.data
y = faces.target

# thus, need to create data w shape (7 * 140, 224 * 224) for total # of samples
# and each row = pixel of photo
# target = labels of all samples

# dividing X, y into train and test data 
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0) 

# training a Naive Bayes classifier 
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB().fit(X_train, y_train) 
gnb_predictions = gnb.predict(X_test) 

# accuracy on X_test 
accuracy = gnb.score(X_test, y_test) 
print(accuracy)

# creating a confusion matrix 
cm = confusion_matrix(y_test, gnb_predictions) 
print(cm)

0.78
[[3 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 0 1 ... 0 0 1]
 ...
 [0 0 0 ... 3 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 2]]
